"""starting to add cascate delete

Revision ID: 026aee58af5e
Revises: 90915151ab7b
Create Date: 2019-06-25 10:47:51.505933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026aee58af5e'
down_revision = '90915151ab7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_student_twitter', table_name='student')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_student_twitter', 'student', ['twitter'], unique=True)
    # ### end Alembic commands ###
