"""added email and password to teachers

Revision ID: 33d8c178e8f6
Revises: e86a7d3b2e30
Create Date: 2019-05-16 10:01:41.564299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d8c178e8f6'
down_revision = 'e86a7d3b2e30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('teacher', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_teacher_email'), 'teacher', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_email'), table_name='teacher')
    op.drop_column('teacher', 'password_hash')
    op.drop_column('teacher', 'email')
    # ### end Alembic commands ###
