"""added reset code

Revision ID: 6c92494e41fe
Revises: f134e7e9c5da
Create Date: 2019-07-03 11:09:00.776703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c92494e41fe'
down_revision = 'f134e7e9c5da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('reset_code', sa.String(length=64), nullable=True))
    op.add_column('teacher', sa.Column('reset_code', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'reset_code')
    op.drop_column('student', 'reset_code')
    # ### end Alembic commands ###
