"""added student grade

Revision ID: 7bafdfc4dbce
Revises: b020a61efbbb
Create Date: 2019-05-29 09:35:06.304734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bafdfc4dbce'
down_revision = 'b020a61efbbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('grade', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'grade')
    # ### end Alembic commands ###
