"""team size

Revision ID: 90915151ab7b
Revises: e757280228e7
Create Date: 2019-06-10 08:32:15.263172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90915151ab7b'
down_revision = 'e757280228e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sport', sa.Column('max_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sport', 'max_size')
    # ### end Alembic commands ###
