"""starting to add cascate delete4

Revision ID: db32b9ebeee1
Revises: 026aee58af5e
Create Date: 2019-06-25 11:38:50.757438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db32b9ebeee1'
down_revision = '026aee58af5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sport_score', sa.Column('sport_id', sa.Integer(), nullable=True))
    op.drop_constraint('sport_score_sport_fkey', 'sport_score', type_='foreignkey')
    op.create_foreign_key(None, 'sport_score', 'sport', ['sport_id'], ['id'])
    op.drop_column('sport_score', 'sport')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sport_score', sa.Column('sport', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sport_score', type_='foreignkey')
    op.create_foreign_key('sport_score_sport_fkey', 'sport_score', 'sport', ['sport'], ['id'])
    op.drop_column('sport_score', 'sport_id')
    # ### end Alembic commands ###
